[project]
name = "quillion"
version = "1.2.0"
description = "Lightweight reactive UI framework for Python"
readme = "README.md"
authors = []
license = {text = ""}
keywords = ["ui", "reactive", "framework"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
requires-python = ">=3.11"
dependencies = [
    "websockets>=12.0",
]

[project.scripts]
q = "quillion.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ruff",
    "pytest",
    "black",
    "mypy",
]
